name: modified_toast_example
description: A simple example of using the flutter_modified_toast package.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_modified_toast:
    path: ../

flutter:
  uses-material-design: true
